name: New_Build_Deployment
on:
  push:
    branches:
      - refs/heads/main
  workflow_dispatch: {}
  workflow_call: {}
jobs:
  Build_Dev:
    uses: ./.github/workflows/Build_Dev.yml
  Build_NUnitTests:
    uses: ./.github/workflows/Build_NUnitTests.yml
  New_Build_Deployment:
    needs:      
      - Build_Dev
      - Build_NUnitTests
    runs-on: ubuntu-latest
    steps: 
    - run: echo "this New_Build_Deployment test"
