name: ChildGitactionDemo
on:
  workflow_dispatch:
 

jobs: 
  tests:
    uses: ./.github/workflows/GitactionDemo.yml
  deploy:
    name: deploy
    needs: [tests] 
    runs-on: ubuntu-latest
    steps: 
    - run: echo "this second test"
  
    
    
