name: Retry Failed Workflow

on:
  workflow_run:
    workflows:
      - .github/workflows/testScript.yml
    types:
      - completed

jobs:
  retry:
    runs-on: ubuntu-latest
    steps:
      - name: Check Workflow Conclusion Status
        run: |
          if [[ "${{ github.workflow_run.conclusion }}" == "failed" ]]; then
            echo "Workflow failed, retrying..."
          else
            echo "Workflow succeeded, no need to retry."
            exit 0
          fi
      - name: Retry Workflow
        uses: nick-fields/retry@v2.8.3
        with:
          max_attempts: 3
          retry_wait_seconds: 30
          continue_on_error: true
          shell: cmd
          command: >-
           echo "this is
                 a test"
