name: Build_NUnitTests
on:
  push:
    branches:
      - refs/heads/main
  workflow_dispatch: {}
  workflow_call: {}
jobs:
  Build_NUnitTests:
    needs:
      - get-cluster
    runs-on: '${{needs.get-cluster.outputs.cluster}}'
    steps: []
  get-cluster:
    runs-on:
      - self-hosted
      - linux
    outputs:
      cluster: ${{ steps.get-cluster-step.outputs.cluster}}
    steps:
      - id: get-cluster-step
        run: |-
          echo - n "::set-output name=cluster::cluster="; echo 
          ${{secrets.CLUSTER_NAME}} | base64 --decode
