name: Build_Manual
on:
  push:
    branches:
      - refs/heads/main
  workflow_dispatch: {}
  workflow_call: {}
jobs:
  Build_Manual:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        max-attempts: [1,2,3]
    steps:
      - name: step1
        if: ${{ job.status!= 'sucess' && matrix.max-attempts>1}}       
    
      - run: |
           echo "this Build_Manual test"
           exit 1
 
