name: Build_NUnitTests
on:
  push:
    branches:
      - refs/heads/main
  workflow_dispatch: {}
  workflow_call: {}
jobs:
  Build_NUnitTests:
    runs-on: ubuntu-latest
    steps: 
    - run: echo "this second test"
