name: Child_workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Your build and test steps here

      - name: Trigger Workflow Dispatch
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            # Set the GITHUB_TOKEN environment variable to your repository's Personal Access Token or a token with workflow scope.
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/Build_NUnitTests/dispatches" \
              -d '{"ref": "main"}'
          fi
          echo "test is completed"
