name: ChildWorkflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Checkout code
        uses: actions/checkout@v2

      # Your build and test steps here

      - name: Trigger Workflow Dispatch
        id: trigger_dispatch
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            # Set the GITHUB_TOKEN environment variable to your repository's Personal Access Token or a token with workflow scope.
            response=$(curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/actions/workflows/Build_NUnitTests.yml/dispatches" \
              -d "{\"ref\":\"main\",\"inputs\":{\"branch\":\"main\"}}")
            echo $response
            workflow_id=$(echo "$response" | jq -r '.id')
            echo $workflow_id
            echo "::set-output name=workflow_id::$workflow_id"
          fi

      - name: Wait for Workflow to Complete
         workflow_runid=${{ steps.trigger_dispatch.outputs.workflow_id }}
         echo "Workflow workflow_runid:$workflow_runid
        if: steps.trigger_dispatch.outputs.workflow_id != ''
        run: |
          # Set the GITHUB_TOKEN environment variable to your repository's Personal Access Token or a token with workflow scope.
          workflow_id=${{ steps.trigger_dispatch.outputs.workflow_id }}
          url="https://api.github.com/repos/${{ github.repository }}/actions/runs/$workflow_id"
          while : ; do
            response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $url)
            status=$(echo "$response" | jq -r '.status')
            if [ "$status" == "completed" ]; then
              conclusion=$(echo "$response" | jq -r '.conclusion')
              echo "Workflow completed with conclusion: $conclusion"
              # You can add further logic based on the workflow conclusion (success or failure)
              break
            fi
            sleep 10
          done
