name: testScript

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  workflow_call:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the script
        run: bash myscript.sh
