name: UTETestWorkFlow

on:
  push:
    branches:
      - refs/heads/main
  workflow_dispatch: {}


jobs:
  
  check_all_jobs_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run custom script
        run: |
            chmod +x ./.github/workflows/check_status.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: All jobs completed
        run: echo "All jobs completed sucessfully"
