name: UTETestWorkFlow

on: [push]

jobs:
  Build_NUnitTests:
    uses: ./.github/workflows/Build_NUnitTests.yml
  Build_Manual:
    uses: ./.github/workflows/Build_Manual.yml
  New_Build_Deployment:
    uses: ./.github/workflows/New_Build_Deployment.yml
  check_all_jobs_status:
    needs: [Build_NUnitTests, Build_Manual, New_Build_Deployment] 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run custom script
        run: |
           ./.github/workflows/check_status.sh
      - name: All jobs completed
        run: echo "All jobs completed sucessfully"
