name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:    
  

jobs:
  main_job:
    runs-on: ubuntu-latest   
    steps:
      - name: Step 1
        uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}
      - name: Include Reusable Steps        
        uses: ./.github/workflows/Build_NUnitTests.yml@main
        

      
