name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_run:
    workflows: [Build_NUnitTests]
    types: [completed]
  

jobs:
  main_job:
     if: ${{ github.event_name == 'workflow_dispatch' }}
     uses: ./.github/workflows/testScript.yml
     
    
   
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed' 
  second_job:
     needs: main_job
     runs-on: ubuntu-latest
     if: ${{ needs.main_job.outputs.job1-status == 'success' || needs.main_job.conclusion == 'skipped' }}
     steps: 
     - run: echo "this second job test"
   
        

      
