name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_run:
    workflows: [Build_NUnitTests]
    types: [completed]
  

jobs:
  main_job:
     if: ${{ github.event_name == 'workflow_dispatch' }}
     uses: ./.github/workflows/testScript.yml
     
    
   
    
  second_job:
    runs-on: ubuntu-latest
    
    steps: 
    - run: echo "this second job test"
   
        

      
