name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_run:
    workflows: [Build_NUnitTests]
    types: [completed]
  

jobs:
  main_job:
     if: ${{ github.event_name == 'workflow_dispatch' }}
     uses: ./.github/workflows/Build_NUnitTests.yml
     
    
   
    
  second_job:
    runs-on: ubuntu-latest
    needs:
     - main_job
    if: needs.main_job.result == 'success' || needs.main_job.result == 'skipped'
    steps: 
    - run: echo "this Skipped reusable test test"
   
        

      
