name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_run:
    workflows: [Build_NUnitTests]
    types: [completed]
  

jobs:
  main_job:
     if: ${{ github.event_name == 'workflow_dispatch' }}
     uses: ./.github/workflows/Build_NUnitTests.yml
     
    
   
    
  second_job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs:
     - main_job
  
    steps: 
    - run: echo "this Skipped reusable test test"
   
        

      
