ame: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  main_job:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "Step 1 executed in the main job."

      - name: Include Reusable Steps
        uses: ./.github/workflows/Build_NUnitTests.yml
        
